name: nexo
description: >-
  An oasis of local music for older hardware. Nexo offers a responsive
  interface, smooth transitions, and extreme optimization for devices
  with limited resources. FOSS & AI-Maintained.
publish_to: 'none'
version: 0.0.10-beta+42

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ">=3.24.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^5.0.0
  drift_dev: ^2.34.5
  build_runner: ^2.4.9
  flutter_launcher_icons: ^0.14.4

dependencies:
  flutter:
    sdk: flutter
  audio_metadata_reader: ^1.7.0
  drift: ^2.34.3
  path: ^1.9.1
  sqlite3: ^3.5.0
  just_audio: ^0.10.6
  audio_service: ^0.18.19
  flutter_riverpod: ^2.6.1
  path_provider: ^2.1.6
  just_audio_media_kit: ^2.1.0
  media_kit_libs_linux: ^1.2.1
  media_kit_libs_windows_audio: ^1.0.9
  file_picker: 10.3.8
  phosphoricons_flutter: ^1.0.0
  permission_handler: ^11.3.1
  archive: ^3.6.1
  share_plus: ^10.1.4

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icon.png
  fonts:
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit-VariableFont_wght.ttf

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#1A1614"
  adaptive_icon_foreground: "assets/icon_fg.png"
  monochrome_icon_path: "assets/icon_mono.png"
  windows:
    generate: true
    image_path: "assets/icon.png"
    icon_size: 256
  linux:
    generate: true
    image_path: "assets/icon.png"
